---
# vim: set ft=ansible:
#
# Unlocks the system to be unlocked to make permanent changes to the /usr mount
#
- name: Unlock system with hotfix
  command: ostree admin unlock --hotfix

- include: '../../rpm_ostree_status/tasks/main.yml'

- name: Fail if unlocked is not set to hotfix
  fail:
    msg: "Unlock is not set to hotfix"
  when: "'hotfix' not in ros_booted['unlocked']"
