---
  # These values were pulled from RHBZ #1398427
- name: Set facts for role
  set_fact:
    test_dir: /var/opt/quest/vas/vasd
    test_dir_match: "/var/opt/quest/vas/vasd(/.*)?"
    test_context: httpd_config_t

- name: Retrieve original context
  shell: "semanage fcontext -l | grep {{ test_dir|quote }}"
  register: orig_context

  # NB: this may return an error message on Fedora that looks like:
  # 'libsemanage.dbase_llist_query: could not query record value (No such file or directory).'
  # However, the operation will still be successful.  ¯\_(ツ)_/¯
- name: Configure new SELinux context
  command: semanage fcontext -m -t {{ test_context }} {{ test_dir_match }}

- name: Retrieve modified context
  shell: "semanage fcontext -l | grep {{ test_dir|quote }}"
  register: mod_context

- name: Fail if modified context is not correct
  fail:
    msg: "The SELinux context does not appear to be changed!"
  when: test_context not in mod_context.stdout or orig_context.stdout == mod_context.stdout
