---
# vim: set ft=ansible:
#
# This role confirms that the 'firewalld' package/service is correctly
# installed (or not installed) on the host under test.
#
- name: Verify firewalld package is installed
  command: rpm -q firewalld

- name: Verify firewalld is disabled by default
  command: systemctl is-enabled -q firewalld
  register: is_enabled
  failed_when: is_enabled|success

# Because of the declarative nature of Ansible, we don't have to perform
# a second check to see if the service was successfully enabled/started.
# If either of those conditions were not met, the task will fail
- name: Verify firewalld can be started/enabled successfully
  service:
    name: firewalld
    enabled: true
    state: 'started'

- name: Revert firewalld back to stopped/disabled
  service:
    name: firewalld
    enabled: false
    state: 'stopped'

