---
# vim: set ft=ansible:
#
#  This role installs a system container through the atomic install --system
#    command
#
- name: Fail if asi_image is undefined
  when: asi_image is undefined
  fail:
    msg: "asi_image is undefined"

# The `aivc_atomic_install_cmd` is set by the required role:
# `atomic_install_version_check`
- name: Install system container
  command: "{{ aivc_atomic_install_cmd }} {{ asi_image }}"
  register: ais
  retries: 5
  delay: 60
  until: ais|success
