---
# vim: set ft=ansible:
#
#  This role installs a system container through the atomic install --system
#    command
#
- name: Fail if image is undefined
  fail:
    msg: "Image is undefined"
  when: image is undefined

# The `aivc_atomic_install_cmd` is set by the required role:
# `atomic_install_version_check`
- name: Install system container
  command: "{{ aivc_atomic_install_cmd }} {{ image }}"
  register: ais
  retries: 5
  delay: 60
  until: ais|success
