---
# vim: set ft=ansible:
#
- name: Fail if g_osname not set
  fail:
    msg: "The g_osname variable is not defined"
  when: g_osname is not defined

- name: Get list of all containers
  command: docker ps -a
  register: ps_before

- name: Fail if httpd container is not present
  fail:
    msg: "The {{ g_osname }}_httpd container is not present"
  when: "'{{ g_osname}}_httpd' not in ps_before.stdout"

- name: Remove the httpd container
  command: "docker rm {{ g_osname }}_httpd"

- name: Get list of all containers again
  command: docker ps -a
  register: ps_after

- name: Fail if httpd container is present
  fail:
    msg: "The {{ g_osname }}_httpd container is still present"
  when: "'{{ g_osname }}_httpd' in ps_after.stdout"
