---
# vim: set ft=ansible:
#
# Runs a command and optionally checks stdout output
#
# Parameters:
#   cmd (string) - command to run
#   output (string) - optional string to check for in stdout
#                     use caution as it is a substring search
#

- name: Fail if cmd is not defined
  fail:
    msg: "cmd is undefined"
  when: cmd is undefined

- name: Run command
  shell: "{{ cmd }}"
  register: cmd_output

- name: Verify output
  fail:
    msg: "{{ output }} is not in command output"
  when: output is defined and
        output not in cmd_output.stdout
