---
# vim: set ft=ansible:
#
- name: Fail if required docker_version is not defined
  fail:
    msg: "The docker_version undefined"
  when: docker_version is undefined

- name: Set actual docker
  shell: docker version -f \{\{.Server.Version\}\}
  register: actual_docker_version

- name: Check if minimum version is met
  fail:
    msg: "Docker version too old: {{ actual_docker_version.stdout }} < {{ docker_version }}"
  when: actual_docker_version.stdout | version_compare(docker_version, '<')
