---
# vim: set ft=ansible:
#
- name: Fail if docker_major is not defined
  fail:
    msg: "The docker_major variable is undefined"
  when: docker_major is undefined

- name: Fail if docker_minor is not defined
  fail:
    msg: "The docker_minor variable is undefined"
  when: docker_minor is undefined

- name: Set actual docker major version
  shell: docker --version | awk '{ print $3 }' | cut -d. -f1
  register: major_output

- name: Set actual docker minor version
  shell: docker --version | awk '{ print $3 }' | cut -d. -f2
  register: minor_output

- name: Check if Ansible is the correct version (or newer)
  assert:
    that:
      - "{{ major_output.stdout | int }} >= {{ docker_major }}"
      - "{{ minor_output.stdout | int  }} >= {{ docker_minor }}"
