---
# vim: set ft=ansible:
#
# Use this role to specify any strings or phrases that should be considered
# fatal if they appear in the journal of a host under test.
#
dependencies:
  # check for SELinux denials
  - role: journal_search
    js_search_string: 'avc:  denied'
    js_file_prefix: 'audit_avc_denied'
    js_extra_args: '_TRANSPORT=audit'
    tags:
      - audit_avc_denied

  # check for SELinux denials from kernel
  # https://bugzilla.redhat.com/show_bug.cgi?id=1536690
  - role: journal_search
    js_search_string: 'avc:  denied'
    js_file_prefix: 'kernel_avc_denied'
    js_extra_args: '_TRANSPORT=kernel'
    tags:
      - kernel_avc_denied

  # check for kernel Oops
  - role: journal_search
    js_search_string: Oops
    js_file_prefix: 'oops_kernel'
    js_extra_args: '_TRANSPORT=kernel'
    tags:
      - oops_kernel

  # check for unmapped SELinux contexts
  # see https://bugzilla.redhat.com/show_bug.cgi?id=1465650#c8
  - role: journal_search
    js_search_string: unmapped
    js_file_prefix: 'unmapped_selinux'
    js_extra_args: '_TRANSPORT=kernel'
    tags:
      - unmapped_selinux
