cluster:
  hosts:
    - name: testnode
      distro: fedora/26/atomic
  container:
    image: registry.fedoraproject.org/fedora:26

context: fedora/26/atomic

packages:
  - python-virtualenv
  - python-pip
  - git
  - gcc
  - redhat-rpm-config
  - libselinux-python
  - rsync

tests:
  - ./.test_director

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: fedora/27/atomic
  container:
    image: registry.fedoraproject.org/fedora:26

context: fedora/27/atomic

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic
  container:
      image: registry.fedoraproject.org/fedora:26

context: centos/7/atomic

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic/continuous
  container:
      image: registry.fedoraproject.org/fedora:26

context: centos/7/atomic/continuous
