cluster:
  hosts:
    - name: testnode
      distro: fedora/28/atomic
  container:
    image: registry.fedoraproject.org/fedora:28

context: fedora/28/atomic

packages:
  - python-virtualenv
  - python-pip
  - git
  - gcc
  - redhat-rpm-config
  - libselinux-python
  - rsync

tests:
  # permanently set g_docker_latest=false, since Fedora doesn't have
  # a docker-latest
  - ./.test_director -e g_docker_latest=false

---
inherit: true

cluster:
  hosts:
    - name: testnode
      # TODO: switch this to 'stable' F29AH when it releases
      distro: fedora/29/atomic/pungi
      ostree:
        branch: fedora/29/x86_64/testing/atomic-host
  container:
      image: registry.fedoraproject.org/fedora:28

context: fedora/29/atomic

tests:
  # permanently set g_docker_latest=false, since Fedora doesn't have
  # a docker-latest
  - ./.test_director -e g_docker_latest=false

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic/continuous
  container:
      image: registry.fedoraproject.org/fedora:28

context: centos/7/atomic/continuous

tests:
  - ./.test_director

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic
  container:
      image: registry.fedoraproject.org/fedora:28

context: centos/7/atomic

tests:
  - ./.test_director

