cluster:
  hosts:
    - name: testnode
      distro: fedora/26/atomic
  container:
    image: registry.fedoraproject.org/fedora:26

context: fedora/26/atomic

packages:
  - ansible
  - git
  - python2-jmespath

tests:
  - ./.test_director

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: fedora/27/atomic
  container:
    image: registry.fedoraproject.org/fedora:27

context: fedora/27/atomic

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic
  container:
      image: registry.centos.org/centos/centos:7

context: centos/7/atomic

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic/continuous
  container:
      image: registry.centos.org/centos/centos:7

context: centos/7/atomic/continuous
