cluster:
  hosts:
    - name: testnode
      distro: fedora/26/atomic
  container:
    image: registry.fedoraproject.org/fedora:25

context: fedora/26/atomic

packages:
  - ansible
  - git
  - python2-jmespath

tests:
  - ./.test_director

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic
  container:
    image: registry.fedoraproject.org/fedora:25

context: centos/7/atomic

---
inherit: true

cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic/continuous
  container:
    image: registry.fedoraproject.org/fedora:25

context: centos/7/atomic/continuous
