cluster:
  hosts:
    - name: testnode
      distro: centos/7/atomic/alpha
      ostree:
        branch: centos-atomic-host/7/x86_64/devel/smoketested
  container:
    image: fedora:25

packages:
  - ansible

tests:
  - ansible-playbook -vi testnode, common/ans_ah_head-1_deploy.yml
  - ansible-playbook -vi testnode, tests/improved-sanity-test/main.yml
