---
# vim: set ft=ansible:
#
# Parameters:
#   rv_rpms (required) - list of rpms installed on atomic host
#
# This role takes a list of rpms, retrieves the version, and stores it in a
# dict named g_atomic_host
#
- include_tasks: version.yml
  rv_rpm: "{{ item }}"
  with_items: "{{ rv_rpms }}"
