---
# vim: set ft=ansible:
#
# A task for registering via `subscription-manager`.  This role will
# revert the refspec in the origin file if other RHEL streams are used.
#
# It reads a CSV file to extract the values for the options below.
#
# Expects the following variable to be defined:
#  - subscription_file
#
# NOTE: The 'subscription_file' variable lives in roles/redhat_subscription/vars/subscription.yml
#
# NOTE: It is suggested that the value of `subscription_file` point to a file
#       that is in the files directory of (same directory the tasks directory)
#       is located) a role.  This will reduce any difficulties trying to
#       determine the right path for the CSV file.
#
#       ../files/subscription_data.csv

# Below we use string formatting to use a variable as the name of the file in
# the lookup()
# via http://stackoverflow.com/a/34239020
#
  - name: Get the current commit to find the correct origin file to manipulate later...
    command: rpm-ostree status --json
    register: rpm_output

  - name: Convert deployment information into jinja2 json
    set_fact:
      json: "{{ rpm_output.stdout|from_json }}"

  - name: Set version and commit if deployment 0 is booted
    set_fact:
      booted_commit: "{{ json['deployments'][0]['checksum'] }}"
    when: json['deployments'][0] is defined and json['deployments'][0]['booted']

  - name: Set version and commit if deployment 1 is booted
    set_fact:
      booted_commit: "{{ json['deployments'][1]['checksum'] }}"
    when: json['deployments'][1] is defined and json['deployments'][1]['booted']

  - name: Get refspec from origin file
    command: grep refspec /ostree/deploy/rhel-atomic-host/deploy/{{ booted_commit }}.0.origin
    register: refspec

  - name: Fail if subscription_file is not defined
    fail:
      msg: "subscription_file is not defined!"
    when: subscription_file is not defined
    run_once: true

  - name: Register with subscription-manager
    command: >
      subscription-manager register --auto-attach --force
      --baseurl="{{ lookup('csvfile', 'baseurl file={} delimiter=,'.format(subscription_file)) }}"
      --serverurl="{{ lookup('csvfile', 'serverurl file={} delimiter=,'.format(subscription_file)) }}"
      --username="{{ lookup('csvfile', 'username file={} delimiter=,'.format(subscription_file)) }}"
      --password="{{ lookup('csvfile', 'password file={} delimiter=,'.format(subscription_file)) }}"
    register: result
    until: result.rc == 0
    retries: 3
    delay: 5

  - name: disable all repos
    command: subscription-manager repos --disable=*

  - name: enable server, optional, and extras repos
    command: >
      subscription-manager repos
      --enable rhel-7-server-rpms
      --enable rhel-7-server-optional-rpms
      --enable rhel-7-server-extras-rpms

  - name: Mask and stop rhsmcertd
    shell: >
      systemctl mask rhsmcertd && systemctl stop rhsmcertd

  - name: Revert refspec in origin after susbcription if it not the default refspec
    replace:
      dest: /ostree/deploy/rhel-atomic-host/deploy/{{ booted_commit }}.0.origin
      regexp: '^refspec.*$'
      replace: "{{ refspec.stdout }}"
    when: refspec.stdout.find("refspec=rhel-atomic-host") == -1
