---
# vim: set ft=ansible:
#
# Role: epel_rpm_url
#
# Scrapes the html on EPEL for the package name since the name changes with
#  the version.  This should be used after system unlocks using ostree admin
#  unlock or ostree admin unlock --hotfix.
#
# Parameters:
#  rpm_name - short name of the rpm file name
#
# Returns:
#  epel_rpm_url - url for the current version of the rpm_name in EPEL
#

- name: Fail if rpm_name
  fail:
    msg: "rpm_name must be passed into this role/include"
  when: rpm_name is undefined

- name: Set EPEL base url
  set_fact:
    epel_base: "https://download.fedoraproject.org/pub/epel/7/x86_64"

- name: Get subdir url
  set_fact:
    epel_subdir: "{{ epel_base }}/{{ rpm_name[0] }}"

- name: Scrape HTML for package name
  shell: curl -LsSk {{ epel_subdir }}/ | sed -n 's/.*"\({{ rpm_name }}.*.rpm\)\".*/\1/p'
  register: epel_output
  retries: 5
  delay: 60
  until: epel_output|success

- name: Set epel_rpm_url
  set_fact:
    epel_rpm_url: "{{ epel_subdir}}/{{ epel_output.stdout }}"
