---
# vim: set ft=ansible:
#
- name: Set use_container_file_t to be False by default
  set_fact:
    use_container_file_t: False

- name: Check for presence of container_file_t type
  command: seinfo --type=container_file_t
  register: seinfo
  ignore_errors: True

- name: Set use_container_file_t to True when present
  set_fact:
    use_container_file_t: True
  when: seinfo.rc == 0

- name: Fail if vaf_filename is not defined
  fail:
    msg: "vaf_filename is undefined"
  when: vaf_filename is undefined

- name: Fail if vaf_dirname is not defined
  fail:
    msg: "vaf_dirname is undefined"
  when: vaf_dirname is undefined

- name: Make directory in /var with svirt_sandbox_file_t
  file:
    path: "/var/{{ vaf_dirname }}"
    state: directory
    mode: 0755
    setype: svirt_sandbox_file_t
  when: not use_container_file_t

- name: Make directory in /var with container_file_t
  file:
    path: "/var/{{ vaf_dirname }}"
    state: directory
    mode: 0755
    setype: container_file_t
  when: use_container_file_t

- name: Add file in new directory
  shell: "echo $(sha256sum /etc/passwd) > {{ vaf_filename | quote }}"
  args:
    chdir: "/var/{{ vaf_dirname }}"
