---
# provide an empty iterator when a list is not provided
# http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals
- include: ../../../common/ans_reboot.yaml
  vars:
    services: "{{ wait_for_services|default([]) }}"
