---
# vim: set ft=ansible:
#
- name: Include distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"

- name: Fail if required variables are not defined
  fail:
    msg: "The required variables are not defined.  Check files under roles/docker_storage_verify/vars"
  when: driver is undefined

  # Maximum efficiency!  The output from 'docker info' contains a line:
  #
  #   Storage Driver: <value>
  #
  # So we grab the value, split on the colon + space, and compare the value
  # to the expected driver.  All in one task!
- name: Check Docker storage driver
  shell: docker info | grep '^Storage Driver'
  register: storage_driver
  failed_when: "'{{ storage_driver.stdout.split(': ')[1] }}' != '{{ driver }}'"

- name: Check for F25 Docker mount
  command: findmnt /var/lib/docker/devicemapper
  when:
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version <= '25'

- name: Check for F26 Docker mount
  command: findmnt /var/lib/docker
  when:
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version == '26'

- name: Check for Fedora Rawhide Docker mount
  command: findmnt /var/lib/docker/containers
  when:
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version > '26'
