---
# vim: set ft=ansible:
#
- name: Set storage driver
  set_fact:
    storage_driver: 'overlay2'

- name: Set storage driver for CAHC
  when: ansible_distribution == 'CentOSDev'
  set_fact:
    storage_driver: 'devicemapper'

- name: Check Docker storage driver
  command: "docker info --format {% raw %}{{.Driver}}{% endraw %}"
  register: di
  failed_when: "di.stdout != storage_driver"

- name: Check for Docker mount
  command: findmnt /var/lib/docker/containers
