---
# vim: set ft=ansible:
#
# Removes package using rpm
#
- name: Fail if rpm_name
  fail:
    msg: "rpm_name is undefined"
  when: rpm_name is undefined

- name: Uninstall {{ rpm_name }}
  command:  rpm -e {{ rpm_name }}
