---
# vim: set ft=ansible:
#
# The behavior changed with this commit:
# https://github.com/projectatomic/atomic/commit/b5f07baa6c54c2bc74079797b80a109a8d10873a
- name: Setup atomic install command (pre v1.19.1)
  set_fact:
    aivc_atomic_install_cmd: "atomic install --system --system-package no "

# g_atomic_host['atomic'] comes from rpm_version in this roles dependencies
- name: Setup atomic install command (post v1.19.1)
  set_fact:
    aivc_atomic_install_cmd: "atomic install --system "
  when: g_atomic_host['atomic'] | version_compare('1.19.1', '>=')

