---
# vim: set ft=ansible:
# role: rpm_ostree_uninstall_verify
#
# This role verifies that a package is uninstall after rpm-ostree uninstall
#  by checking the package name is not in rpm-ostree status output and verifying
#  that the binary not available using which
#
# Parameter:
#   rouv_package_name - the name of a single package
#   rouv_binary_name - the name of a binary (optional)
#
# Requirements:
#  This role must be run after the reboot following rpm-ostree install of a package
#
# !!! WARNING!!!
#   If you plan on using this role multiple times in a playbook, you should
#   explicitly provide values for 'rouv_package_name' and 'rouv_binary_name'
#   in order to avoid existing values in the playbook namespace to be reused
#   across the roles.
#
- name: Fail if no packages specified
  fail:
    msg: "No packages specified"
  when: rouv_package_name is undefined

# The 'binary' fact can be set to something other than the package name
# if needed
- name: Setup binary fact
  set_fact:
    rouv_binary_name: "{{ rouv_binary_name if rouv_binary_name is defined else rouv_package_name }}"

- name: Get rpm-ostree status --json output
  command: rpm-ostree status --json
  register: installed

- name: Convert rpm-ostree status output to jinja2 json
  set_fact:
    installed_json: "{{ installed.stdout | from_json }}"

# This is a hack for packages being displayed in rpm-ostree v2017.3 that should
# be fixed in v2017.4.  Once all streams are at v2017.4 we can fix this.  See
# https://github.com/projectatomic/rpm-ostree/pull/670
- name: Set packages when deployment 0 is booted
  set_fact:
    installed_pkgs: "{{ installed_json['deployments'][0]['packages'] if installed_json['deployments'][0]['packages'] is defined else {} }}"
  when: installed_json['deployments'][0]['booted']

- name: Set packages when deployment 1 is booted
  set_fact:
    installed_pkgs: "{{ installed_json['deployments'][1]['packages'] if installed_json['deployments'][1]['packages'] is defined else {} }}"
  when:  installed_json['deployments'][1]['booted']

- name: Fail if packages not found in rpm-ostree status output
  fail:
    msg: "Packages not found in rpm-ostree status output"
  when: installed_pkgs is undefined

- name: Fail if {{ rouv_package_name }} is in rpm-ostree status output
  fail:
    msg: "{{ rouv_package_name }} in rpm-ostree status output"
  when: "'{{ rouv_package_name }}' in installed_pkgs"

- name: Fail if binary for {{ rouv_binary_name }} is installed
  command: command -v {{ rouv_binary_name }}
  register: binary
  failed_when: binary.rc != 1

- name: Fail if {{ rouv_package_name }} is in rpmdb
  command: rpm -q {{ rouv_package_name }}
  register: rpm
  failed_when: rpm.rc != 1
