---
# vim: set ft=ansible:
# role: rpm_ostree_uninstall_verify
#
# This role verifies that a package is uninstall after rpm-ostree uninstall
#  by checking the package name is not in rpm-ostree status output and verifying
#  that the binary not available using which
#
# Parameter:
#   package - the name of a single package
#
# Requirements:
#  Package must install a binary that is the same as the package name
#    i.e. rpm-ostree uninstall wget installs a binary named wget
#  This role must be run after the reboot following rpm-ostree install of a package
#

- name: Fail if no packages specified
  fail:
    msg: "No packages specified"
  when: package is undefined

- name: Get rpm-ostree status --json output
  command: rpm-ostree status --json
  register: installed

- name: Convert rpm-ostree status output to jinja2 json
  set_fact:
    installed_json: "{{ installed.stdout | from_json }}"

# This is a hack for packages being displayed in rpm-ostree v2017.3 that should
# be fixed in v2017.4.  Once all streams are at v2017.4 we can fix this.  See
# https://github.com/projectatomic/rpm-ostree/pull/670
- name: Set packages when deployment 0 is booted
  set_fact:
    installed_pkgs: "{{ installed_json['deployments'][0]['packages'] if installed_json['deployments'][0]['packages'] is defined else {} }}"
  when: installed_json['deployments'][0]['booted']

- name: Set packages when deployment 1 is booted
  set_fact:
    installed_pkgs: "{{ installed_json['deployments'][1]['packages'] if installed_json['deployments'][1]['packages'] is defined else {} }}"
  when:  installed_json['deployments'][1]['booted']

- name: Fail if packages not found in rpm-ostree status output
  fail:
    msg: "Packages not found in rpm-ostree status output"
  when: installed_pkgs is undefined

- name: Fail if {{ package }} is in rpm-ostree status output
  fail:
    msg: "{{ package }} in rpm-ostree status output"
  when: "'{{ package }}' in installed_pkgs"

- name: Fail if binary for {{ package }} is installed
  command: command -v {{ package }}
  register: binary
  failed_when: binary.rc != 1

- name: Fail if {{ package }} is in rpmdb
  command: rpm -q {{ package }}
  register: rpm
  failed_when: rpm.rc != 1
