---
# vim: set ft=ansible:
#
- name: Fail if uvm_uid is not defined
  when: uvm_uid is undefined
  fail:
    msg: "uvm_uid is undefined"

- name: Set regex pattern
  set_fact:
    regex_pattern: "^atomic-user-{{ g_uid1 }}:x:{{ g_uid1 }}:{{ g_uid1 }}::{{ '\\(/var\\)\\?' | regex_escape() }}/home/atomic-user-{{ g_uid1 }}:/bin/bash"

- name: Check to see if the user is in /etc/passwd
  command: "grep -e {{ regex_pattern }} /etc/passwd"
  register: grep_user
  failed_when: grep_user.rc != 1
