---
# vim: set ft=ansible:
#
# This role will rebase to another deployment.  If a remote_url is specified
# the remote will be added before rebasing
#
# rpm-ostree rebase
#   params:
#     remote_name (required) name for remote
#     refspec (required) remote refspec
#     remote_url (optional) remote url will trigger adding of remote
#     commit (optional) rebase to this commit
#
- name: Fail if remote_name or refspec is not defined
  fail:
    msg: "remote_name or refspec is not defined"
  when: remote_name is undefined or
        refspec is undefined

- name: Add remote
  command: ostree remote add --no-gpg-verify {{ remote_name }} {{ remote_url }}
  when: remote_url is defined

- name: Rebase
  command: rpm-ostree rebase {{ remote_name }}:{{ refspec }}
  register: rebase
  retries: 5
  delay: 60
  until: rebase|success
  when: commit is undefined

- name: Rebase
  command: rpm-ostree rebase {{ remote_name }}:{{ refspec }} {{ commit }}
  register: rebase
  retries: 5
  delay: 60
  until: rebase|success
  when: commit is defined

