---
# vim: set ft=ansible:
#
#  This role uninstalls a system container (by name) through the atomic install
#    command
#
- name: Fail if name is undefined
  when: name is undefined
  fail:
    msg: "Name is undefined"

- name: Uninstall system container
  command: atomic uninstall {{ name }}
