---
# vim: set ft=ansible:
#
#  This role uninstalls a system container (by name) through the atomic install
#    command
#
- name: Fail if asu_name is undefined
  when: asu_name is undefined
  fail:
    msg: "asu_name is undefined"

- name: Uninstall system container
  command: atomic uninstall {{ asu_name }}
