---
# vim: set ft=ansible:
#
# This role will search the journal from the latest boot for the string
# supplied as an argument.  It can optionally fail if the string is found.
#
# Parameters:
#   search_string (string) - string to search the journal for
#   fail_if_found (bool) - cause the role to fail if the string is found (optional)
#
- name: Fail if the 'search_string' is undefined
  fail:
    msg: "The variable 'search_string' is undefined"
  when: search_string is undefined

- name: Setup "fail_if_found" variable
  set_fact:
    fif: "{{ fail_if_found | default(false) | bool }}"

#
# We hide the stdout of this task, since the journal could be 1000s of lines
# This method is used because if we did something like:
#
#  'journalctl -b | grep foo'
#
# ...that command itself would show up in the journal because of how Ansible
# executes commands on the host.
#
- name: Grab the journal
  command: journalctl -b --no-pager
  register: j
  no_log: true

- name: Set the found_string fact
  set_fact:
    found_string: "{{ j.stdout | search(search_string) }}"

- name: Search for string in the journal
  fail:
    msg: "Unable to find string '{{ search_string }}' in the journal"
  when:
    - not fif
    - not found_string

# We scrape the journal manually after the fact because the contents of the
# 'shell:' command below will end up in the journal when it is run on the
# host under test.  Since the test should fail and abort any other plays
# in the playbook, it should be safe to pollute the journal like this.
#
# Additionally, this is not in a 'block:' statement because apparently you
# can't include a 'fail:' statement inside a block.  ¯\_(ツ)_/¯
- name: Grep the journal again for matching strings
  shell: "journalctl -b | grep {{ search_string | quote }}"
  when:
    - fif
    - found_string

- name: Fail if the string was found in the journal
  fail:
    msg: "Found the string '{{ search_string }}' in the journal"
  when:
    - fif
    - found_string
