---
distro_files:
  - { key: '/usr/bin/docker', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-containerd', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-containerd-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-containerd-shim', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-containerd-shim-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-ctr-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/dockerd', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/dockerd-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/dockerd-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/docker-latest-storage-setup', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/bin/container-storage-setup', value: 'system_u:object_r:bin_t:s0' }
  - { key: '/usr/libexec/docker/docker-containerd-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-containerd-shim-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-ctr-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-init-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-lvm-plugin', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-novolume-plugin', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-proxy-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-proxy-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-runc-current', value: 'system_u:object_r:container_runtime_exec_t:s0' }
  - { key: '/usr/libexec/docker/docker-runc-latest', value: 'system_u:object_r:container_runtime_exec_t:s0' }

distro_procs:
  - { key: 'docker', value: 'system_u:system_r:container_runtime_t:s0' }
