---
etc_files:
  - name: net_conf
    files:
      - '/etc/hosts'
      - '/etc/hosts.allow'
      - '/etc/hosts.deny'
    label: 'system_u:object_r:net_conf_t:s0'

  - name: passwd
    files:
      - '/etc/group'
      - '/etc/group-'
      - '/etc/passwd'
      - '/etc/passwd-'
    label: 'system_u:object_r:passwd_file_t:s0'

  - name: shadow
    files:
      - '/etc/gshadow'
      - '/etc/gshadow-'
      - '/etc/shadow'
      - '/etc/shadow-'
    label: 'system_u:object_r:shadow_t:s0'


# Until RHBZ #1381588 is fixed, we are removing the `/sysroot` entry from
# this list.
mountpoints:
  - '/boot'
  - '/usr'
  - '/var'

services:
  - name: docker
    # This is the intersection of the three sets of files provided by the
    # docker and docker-common packages per distro.  I used:
    #
    # $ rpm -qf docker docker-common | grep -E 'bin|libexec'
    #
    # ...to generate the lists.
    files:
      - '/usr/bin/docker'
      - '/usr/bin/dockerd-current'
      - '/usr/bin/docker-storage-setup'
      - '/usr/libexec/docker/docker-proxy-current'
      - '/usr/libexec/docker/docker-runc-current'
    file_label: 'system_u:object_r:container_runtime_exec_t:s0'
    procs:
      - 'docker'
    proc_label: 'system_u:system_r:container_runtime_t:s0'

  - name: NetworkManager
    files:
      - '/usr/sbin/NetworkManager'
    file_label: 'system_u:object_r:NetworkManager_exec_t:s0'
    procs:
      - 'NetworkManager'
    proc_label: 'system_u:system_r:NetworkManager_t:s0'

  - name: rpm-ostree
    files:
      - '/usr/bin/ostree'
      - '/usr/bin/rpm-ostree'
      - '/usr/libexec/rpm-ostreed'
    file_label: 'system_u:object_r:install_exec_t:s0'
    procs:
      - 'rpm-ostreed'
    proc_label: 'system_u:system_r:install_t:s0'

  - name: sshd
    files:
      - '/usr/sbin/sshd'
    file_label: 'system_u:object_r:sshd_exec_t:s0'
    procs:
      - 'sshd'
    proc_label: 'system_u:system_r:sshd_t:s0-s0'
