---
# vim: set ft=ansible:
#
#  This role checks that the specified image is in the atomic containers
#   list output
#
- name: Fail if image is undefined
  fail:
    msg: "Image is undefined"
  when: image is undefined

- name: Get atomic containers list output
  command: atomic containers list --all --no-trunc
  register: acl_output

- name: Fail if image is not in list output
  fail:
    msg: |
      Expected: {{ image }} is in atomic containers list output
      Actual: {{ acl_output.stdout }}
  when: image not in acl_output.stdout
