---
# vim: set ft=ansible:
#
popular_images:
  - docker.io/alpine
  - docker.io/busybox
  - docker.io/ubuntu
  - registry.fedoraproject.org/fedora
  - registry.centos.org/centos/centos
  - registry.access.redhat.com/rhel
