---
# vim: set ft=ansible:
#
# Deletes users on a system with prejudice.
#
# Parameters:
#   - ud_users - list of users to be deleted
#
- name: Fail if ud_users is not defined
  when: ud_users is undefined
  fail:
    msg: |
      You must supply at least one user as a value for 'ud_users'

- name: Delete users
  command: "userdel -r -f {{ item }}"
  ignore_errors: true
  with_items:
    - "{{ ud_users }}"
