---
# vim: set ft=ansible:
#
- name: Verify that the RPM database is intact
  shell: rpm -qa | wc -l
  register: rpmdb

- name: Fail if the RPM database is broken
  when: rpmdb.stdout|int <= 0 or rpmdb.rc != 0
  fail:
    msg: "The RPM database is not usable"
