---
# vim: set ft=ansible:
# role: rpm_ostree_uninstall
#
# This role uninstalls packages using rpm-ostree uninstall
#
# Parameters:
#  rou_packages - string of one or more packages separated by a space
#                 or use the 'all' keyword to uninstall everything
#  rou_reboot - boolean - pass -r flag to install command
#

- name: Fail if no packages specified
  when: rou_packages is undefined
  fail:
    msg: "No packages specified"

- name: Fail if reboot is undefined
  when: rou_reboot is undefined
  fail:
    msg: "Reboot is not defined"

- when: rou_packages == "all"
  block:
    # This role provides the following variables:
    #  - ros: result of 'rpm-ostree status --json'
    #  - ros_json: ros.stdout piped through the from_json filter
    #  - ros_num_deployments:  number of deployments on host
    #  - ros_booted: JSON object of the booted deployment
    #  - ros_not_booted: JSON object of the not booted deployment
    - name: Get rpm-ostree status output
      import_role:
        name: rpm_ostree_status

    # If the 'packages' key has a value, we create a list of packages to
    # uninstall, otherwise skip it
    - name: Get all installed packages
      when: ros_booted['packages']|length > 0
      set_fact:
        all_installed: "{{ ros_booted['packages']|join(' ') }}"

# Check to see if 'all_installed' was defined above, otherwise we use the
# original value of 'packages'.  It could be 'all', which means we want to
# uninstall all packages but there were no packages actually installed.
#
# Hat tip to @mike-nguyen for the logic to do this
- name: Setup 'rm_packages' variable
  set_fact:
    rm_packages: "{{ all_installed if all_installed is defined else rou_packages }}"

- name: Uninstall {{ rm_packages }}
  when: not rou_reboot and rm_packages != "all"
  command: rpm-ostree uninstall {{ rm_packages }}

- name: Uninstall {{ rm_packages }} and reboot
  when: rou_reboot and rm_packages != "all"
  command: rpm-ostree uninstall {{ rm_packages }} -r
  async: 60
  poll: 0
  ignore_errors: true

- name: Reboot if necessary
  when: rou_reboot and rm_packages != "all"
  import_role:
    name: reboot
  vars:
    skip_shutdown: true # shutdown was already initiated
