---
# vim: set ft=ansible:
# role: rpm_ostree_uninstall
#
# This role uninstalls packages using rpm-ostree uninstall
#
# Parameters:
#  packages - string of one or more packages separated by a space
#  reboot - boolean - pass -r flag to install command
#

- name: Fail if no packages specified
  fail:
    msg: "No packages specified"
  when: packages is undefined

- name: Fail if reboot is undefined
  fail:
    msg: "Reboot is not defined"
  when: reboot is undefined

- name: Uninstall {{ packages }}
  command: rpm-ostree uninstall {{ packages }}
  when: not reboot

- name: Uninstall {{ packages }} and reboot
  command: rpm-ostree uninstall {{ packages }} -r
  async: 60
  poll: 0
  when: reboot
  ignore_errors: true

- include: ../../../common/ans_reboot.yml
  vars:
    skip_shutdown: true # shutdown was already initiated
  when: reboot
