---
# vim: set ft=ansible:
#
- name: Determine rpm-ostree version
  block:
    - command: rpm-ostree --version
      register: ros_out

    - set_fact:
        ros_yaml: "{{ ros_out.stdout | from_yaml }}"

    - set_fact:
        ros_version: "{{ ros_yaml['rpm-ostree']['Version'] }}"

- name: Set old livefs command
  set_fact:
    ros_livefs_cmd: "rpm-ostree ex livefs"

- name: Set new livefs command
  when: ros_version | version_compare('2018.9', '>=')
  set_fact:
    ros_livefs_cmd: "rpm-ostree ex livefs --i-like-danger"

- name: Enable livefs
  command: "{{ ros_livefs_cmd }}"
  register: ros_lfs

# Regex to find all the sha256 checksums in the output
- name: Get commits
  set_fact:
    commits: "{{ ros_lfs.stdout|regex_findall('[A-Fa-f0-9]{64}') }}"

# Note: There was an instance where there were three checksums in the message
# so just grab the last two.
- name: Get base and livefs commits
  set_fact:
    rol_base_commit: "{{ commits[-2] }}"
    rol_livefs_commit: "{{ commits[-1] }}"

