---
# vim: set ft=ansible:
#
# pulls image with atomic cli
#
- name: Fail if apl_image is undefined
  fail:
    msg: "apl_image is not defined"
  when: apl_image is undefined

- name: Set options
  set_fact:
    pull_options: "{{ apl_options | default() }}"

- name: Pull image
  command: atomic pull {{ apl_image }} {{ pull_options }}
