---
# vim: set ft=ansible:
#
# pulls image with atomic cli
#
# Required variables:
#  - apl_image: name of image to be pulled (string)
#
# Optional variables:
#  - apl_options: options to be passed to 'atomic pull' (string)
#
- name: Fail if apl_image is undefined
  when: apl_image is undefined
  fail:
    msg: "apl_image is not defined"

- name: Set options
  set_fact:
    pull_options: "{{ apl_options | default() }}"

- name: Pull image
  command: atomic pull {{ apl_image }} {{ pull_options }}
  register: pull
  retries: 6
  delay: 10
  until: pull|success
