---
# vim: set ft=ansible:
#
#   This role verifies the atomic scan command.  It validates the command by
#   checking the output of the command and looking for the log file generated
#   by the scan command.
#
#   Commands:
#   - atomic install
#   - atomic scan
#
- name: Set scanner image (RHEL)
  set_fact:
    scanner_image: "registry.access.redhat.com/rhel7/openscap"
    scanner_type: "openscap"

- name: Set scanner target
  set_fact:
    scanner_target: "registry.access.redhat.com/rhel7"

- name: Install openscap
  command: atomic install {{ scanner_image }}
  register: result

- name: Check installation of openscap
  fail:
    msg="Atomic install was unsuccessful"
  when: "'Installation complete' not in result.stdout"

  # Because the 'atomic install' of the 'rhel7/openscap' image drops a config
  # file in '/etc/atomic.d/' which doesn't use a fully-qualified image name,
  # this causes a problem on non RHEL hosts. See:
  #
  # https://bugzilla.redhat.com/show_bug.cgi?id=1418464
  #
  # We need to work around it until it gets fixed. It's a safe change to make
  # for RHEL hosts too, so let's just do it everywhere.
- name: Modify image name in /etc/atomic.d/openscap
  lineinfile:
    destfile: /etc/atomic.d/openscap
    regexp: '^image_name:*'
    line: 'image_name: registry.access.redhat.com/rhel7/openscap'

  # Use 'docker pull' for now; maybe switch to 'atomic pull' once all the
  # streams have support for v1 schema manifests
- name: Pull scanner target
  command: docker pull {{ scanner_target }}

- name: Run atomic scan
  command: atomic --debug scan --scanner {{ scanner_type }} {{ scanner_target }}
  register: atomic_output

- name: Catch atomic scan failures
  fail:
    msg="Atomic scan failed"
  when: "'Files associated' not in atomic_output.stdout"

- name: Get scanner result directory
  shell: echo {{ atomic_output.stdout | quote }} | awk '/^Files associated/{print $8}' | sed "s/\.[\']*//"
  register: dir

- name: Verify scanner result directory exists
  stat:
    path={{ dir.stdout }}
  register: scan_dir

- name: Fail if result directory does not exist
  fail:
    msg="Scanner result directory does not exist."
  when: scan_dir.stat.exists == False
