---
- name: Remove all the manifests
  file:
    path: "/etc/kubernetes/manifests/{{ item }}"
    state: absent
  with_items:
    - apiserver-pod.json
    - controller-mgr-pod.json
    - scheduler-pod.json

- name: Disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - kube-proxy
    - kubelet

- name: Define kubectl path for F27AH
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version > '26') or
        (ansible_distribution == "CentOSDev")
  set_fact:
    kubectl_path: "/usr/local/bin/kubectl"

- name: Define kubectl path for F26AH, Centos/RHEL
  when: (ansible_distribution == "RedHat") or
        (ansible_distribution == "Fedora" and ansible_distribution_major_version < '27') or
        (ansible_distribution == "CentOS")
  set_fact:
    kubectl_path: "/usr/bin/kubectl"


- name: Remove all services
  command: "{{ kubectl_path }} delete svc --all"

- name: Remove all RCs
  command: "{{ kubectl_path }} delete rc --all"

- name: Remove all pods
  command: "{{ kubectl_path }} delete po --all"
