---
# vim: set ft=ansible:
#
#   This role verifies the atomic pull, run, and stop commands.  The validation
#   of the atomic commands is done against docker.
#
#   Commands:
#   - atomic pull
#   - atomic run
#   - atomic stop
#
- name: Get atomic major version
  shell: atomic --version 2>&1 | cut -d. -f1
  register: atomic_major

- name: Get atomic minor version
  shell: atomic --version 2>&1 | cut -d. -f2
  register: atomic_minor

- name: Pull busybox
  command: atomic pull busybox

- name: Set atomic images command for 1.12 and older
  set_fact:
    atomic_images: "atomic images"
  when: (atomic_minor.stdout|int) < 12 and (atomic_major.stdout|int) == 1

- name: Set atomic images command for 1.12 and newer
  set_fact:
    atomic_images: "atomic images list"
  when: (atomic_minor.stdout|int) >= 12 and (atomic_major.stdout|int) == 1

- name: Get atomic images
  command: "{{ atomic_images }}"
  register: aio

- name: Fail if busybox is not in atomic images output
  fail:
    msg="busybox is not in atomic images output"
  when: "'busybox' not in aio.stdout"
