---
# vim: set ft=ansible:
#
# Removes an image from the host
#
# Required variables:
#  - drmi_image:  name of the image to be removed
#
- name: Fail if drmi_image
  when: drmi_image is undefined
  fail:
    msg: "drmi_image is not defined"

- name: Set options
  set_fact:
    del_options: "{{ drmi_options | default() }}"

- name: Delete image
  command: docker rmi {{ drmi_image }} {{ del_options }}
