---
# vim: set ft=ansible:
#
- name: Fail if drmi_image_name is not defined
  when: drmi_image_name is not defined
  fail:
    msg: "The variable drmi_image_name must be defined"

- name: Get all the docker images
  command: docker images
  register: images_before

- name: Fail if the image is not present
  when: drmi_image_name not in images_before.stdout
  fail:
    msg: |
      Expected: {{ drmi_image_name}} container is in docker images
      Actual: docker images {{ images_before.stdout }}

- name: Remove the image
  command: "docker rmi -f {{ drmi_image_name }}"

- name: Get the docker images against
  command: docker images
  register: images_after

- name: Fail if the image is present
  when: drmi_image_name in images_after.stdout
  fail:
    msg: |
      Expected: {{ drmi_image_name }} is removed from docker images
      Actual: docker images: {{ images_after.stdout }}
