---
# vim: set ft=ansible:
#
# Verifies that a package is installed either through package layering or
#  through rpm package manager.
#
# Parameters:
#   rpm_name (required) - string - rpm name
#   check_binary (optional) boolean - checks that a binary with the same name exists
#
- name: Fail if rpm_name is undefined
  fail:
    msg: "rpm_name must be passed into this role/include"
  when: rpm_name is undefined

- name: Check for {{ rpm_name }} binary
  command: command -v {{ rpm_name }}
  when: check_binary is not defined or check_binary

- name: Check {{ rpm_name }} in rpmdb
  command: rpm -q {{ rpm_name }}
