---
# vim: set ft=ansible:
#
# Verifies that a package is installed either through package layering or
#  through rpm package manager.
#
# Requirements:
# - The package installed must have a binary with the same name
#   i.e. rpm -i htop installs the binary htop
#
- name: Fail if rpm_name is undefined
  fail:
    msg: "rpm_name must be passed into this role/include"
  when: rpm_name is undefined

- name: Check for {{ rpm_name }} binary
  command: command -v {{ rpm_name }}

- name: Check {{ rpm_name }} in rpmdb
  command: rpm -q {{ rpm_name }}
